name: Unit Test
on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install pipenv -y
        pipenv install --dev
    - name: Test with unittest2
      run: |
        pipenv run bash -c "coverage run -m unittest2 discover -s test/unit -t ."
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        verbose: false